### PR TITLE
Updated copyright year

### PR DESCRIPTION
**Pull request by vijaygopal1234**

### CODE REVIEW

**Comment by rhysd** [comment]
Please explain why I need to update the year in copyright notice. If my understanding is correct, I don't need.

**Comment by rhysd** [comment]
ref: https://stackoverflow.com/a/2391555/5148945

**Comment by vijaygopal1234** [comment]
The reason I suggested the change was because there was an inconsistency in the dates. It looks like you are correct regarding the date used, but I would changed it to either 2014 or 2015.

**Comment by rhysd** [comment]
Thanks for pointing out. From Git log, 2014 is correct.

**Pull request closed without merging**
